2024-12-07 14:15:57,055 - root - INFO - "test_challenge" выполнен успешно
2024-12-07 14:15:57,055 - root - WARNING - Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Ke27\UrbanProjects\UrbanTasks\tests_12_4.py", line 68, in test_run
    runner = Runner(5, speed=10)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ke27\UrbanProjects\UrbanTasks\tests_12_4.py", line 13, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-07 14:15:57,056 - root - WARNING - Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Ke27\UrbanProjects\UrbanTasks\tests_12_4.py", line 61, in test_walk
    runner = Runner("Runner", speed=-1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ke27\UrbanProjects\UrbanTasks\tests_12_4.py", line 18, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
